name: evently_vendor
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.12.0
  flutter: ^3.44.0

dependencies:
  app_ui:
    path: packages/app_ui
  bloc: ^9.2.1
  business_repository:
    path: packages/business_repository
  database_client:
    path: packages/database_client
  equatable: ^2.1.0
  firebase_core: ^4.13.0
  firebase_messaging: ^16.6.0
  firebase_notifications_client:
    path: packages/firebase_notifications_client
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^8.2.1
  intl: ^0.20.2
  notifications_client:
    path: packages/notifications_client
  notifications_repository:
    path: packages/notifications_repository
  shared:
    path: packages/shared
  supabase_flutter: ^2.17.2
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_lint: ^0.4.1
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.24
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^10.3.0

flutter:
  generate: true
  uses-material-design: true
